"""add is_updating for repos

Revision ID: 11c965e8acc9
Revises: 
Create Date: 2016-02-25 07:45:16.994206

"""

# revision identifiers, used by Alembic.
revision = '11c965e8acc9'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('is_updating', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'is_updating')
    ### end Alembic commands ###
