"""adds sha1 to repo and binary

Revision ID: 375985186100
Revises: 53483b1161b
Create Date: 2016-06-10 10:18:51.037610

"""

# revision identifiers, used by Alembic.
revision = '375985186100'
down_revision = '53483b1161b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binaries', sa.Column('sha1', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_binaries_sha1'), 'binaries', ['sha1'], unique=False)
    op.add_column('repos', sa.Column('sha1', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_repos_sha1'), 'repos', ['sha1'], unique=False)
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repos_sha1'), table_name='repos')
    op.drop_column('repos', 'sha1')
    op.drop_index(op.f('ix_binaries_sha1'), table_name='binaries')
    op.drop_column('binaries', 'sha1')
    ### end Alembic commands ###
