"""Adds Repo.extra

Revision ID: 4021ff3a9dc5
Revises: 4ee54bf1cca3
Create Date: 2016-08-29 16:09:41.853490

"""

# revision identifiers, used by Alembic.
revision = '4021ff3a9dc5'
down_revision = '4ee54bf1cca3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from chacra import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('extra', models.types.JSONType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'extra')
    ### end Alembic commands ###
