"""add flavors for repos and binaries

Revision ID: 4ee54bf1cca3
Revises: 432dc36d3105
Create Date: 2016-08-02 10:30:19.377335

"""

# revision identifiers, used by Alembic.
revision = '4ee54bf1cca3'
down_revision = '432dc36d3105'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binaries', sa.Column('flavor', sa.String(length=256), nullable=False, server_default='default'))
    op.create_index(op.f('ix_binaries_flavor'), 'binaries', ['flavor'], unique=False)
    op.add_column('repos', sa.Column('flavor', sa.String(length=256), nullable=False, server_default='default'))
    op.create_index(op.f('ix_repos_flavor'), 'repos', ['flavor'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repos_flavor'), table_name='repos')
    op.drop_column('repos', 'flavor')
    op.drop_index(op.f('ix_binaries_flavor'), table_name='binaries')
    op.drop_column('binaries', 'flavor')
    ### end Alembic commands ###
