"""BigInteger size

Revision ID: 52d176771ae6
Revises: 4021ff3a9dc5
Create Date: 2019-01-22 16:47:06.695469

"""

# revision identifiers, used by Alembic.
revision = '52d176771ae6'
down_revision = '4021ff3a9dc5'
branch_labels = None
depends_on = None
from sqlalchemy import BigInteger, Integer

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('binaries', 'size', type_=BigInteger)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('binaries', 'size', type_=Integer)
    # ### end Alembic commands ###
