"""Add is_queued field for repos

Revision ID: 53483b1161b
Revises: 11c965e8acc9
Create Date: 2016-06-07 15:06:14.618478

"""

# revision identifiers, used by Alembic.
revision = '53483b1161b'
down_revision = '11c965e8acc9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('is_queued', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'is_queued')
    ### end Alembic commands ###
