- name: update the apt cache
  become: true
  apt:
    update_cache: true

- name: install pkg-config
  become: true
  apt:
    name: pkg-config

- name: install erlang
  become: true
  apt:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
    state: present

- name: install rabbitmq-server
  become: true
  apt:
    name: rabbitmq-server
    state: present

- name: ensure rabbitmq is running and enabled
  become: true
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: enable web management for rabbit
  become: true
  command: rabbitmq-plugins enable rabbitmq_management
