---
- name: add the rabbitmq signing key
  become: true
  shell:
    cmd: "curl -1sLf 'https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA' | sudo gpg --dearmor > /usr/share/keyrings/com.rabbitmq.team.gpg"

- name: add the rabbitmq official repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb1.rabbitmq.com/rabbitmq-erlang/ubuntu/{{ ansible_lsb.codename }} {{ ansible_lsb.codename }} main"
    state: present

- name: update the apt cache
  become: true
  apt:
    update_cache: true

- name: install pkg-config
  become: true
  apt:
    name: pkg-config

- name: install erlang
  become: true
  apt:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
    state: present

- name: install rabbitmq-server
  become: true
  apt:
    name: rabbitmq-server
    state: present

- name: ensure rabbitmq is running and enabled
  become: true
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: enable web management for rabbit
  become: true
  command: rabbitmq-plugins enable rabbitmq_management
