- name: update the apt cache
  become: true
  apt:
    update_cache: true

- name: install pkg-config
  become: true
  apt:
    name: pkg-config

- name: install rabbitmq-server
  become: true
  apt:
    name: rabbitmq-server
    state: present

- name: ensure rabbitmq is running and enabled
  become: true
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: enable web management for rabbit
  become: true
  command: rabbitmq-plugins enable rabbitmq_management
