apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chacra-shared-rwx
  namespace: chacra
  labels:
    app: chacra
spec:
  storageClassName: cephfs-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
