# openshift/deploy/sa-rbac-bootstrap.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chacra-bootstrap
  namespace: chacra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chacra-bootstrap-secrets-role
  namespace: chacra
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create","update","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chacra-bootstrap-secrets-rb
  namespace: chacra
subjects:
  - kind: ServiceAccount
    name: chacra-bootstrap
    namespace: chacra
roleRef:
  kind: Role
  name: chacra-bootstrap-secrets-role
  apiGroup: rbac.authorization.k8s.io
